version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t htmlapp -t dakshkotian/htmlapp:latest .
            echo $DOCKER_PASSWORD | docker login -u dakshkotian --password-stdin
            docker push dakshkotian/htmlapp:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
